require: rubocop-rspec

AllCops:
  Exclude:
    - 'Rakefile'
    - 'bin/*'

Metrics/BlockLength:
  Exclude:
    - 'calc.gemspec'
    - spec/**/*

RSpec/DescribeClass:
  Exclude:
    - spec/features/**/*
